---
# !!! Ansible managed !!!
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks
# Material Design Icons with mdi-XX: https://pictogrammers.com/library/mdi/
# Simple Icons with si-XX: https://simpleicons.org/

- Social Media:
    - YouTube:
        - icon: si-youtube
          href: https://youtube.com
    - Discord:
        - icon: si-discord
          href: https://discord.com
    - Reddit:
        - icon: si-reddit
          href: https://reddit.com
- Developer:
    - Gitea:
        - icon: si-gitea
          # prettier-ignore
          href: https://gitea.{{HOMEPAGE_VAR_MY_DOMAIN}}
    - Github:
        - icon: si-github
          href: https://github.com/
    - pgAdmin:
        - icon: si-postgresql
          # prettier-ignore
          href: https://pgadmin.{{HOMEPAGE_VAR_MY_DOMAIN}}/pgadmin4
    - Proxmox VE Helper:
        - icon: si-proxmox
          href: https://tteck.github.io/Proxmox
    - Homepage.dev:
        - icon: si-homepage
          href: https://gethomepage.dev
- Gaming:
    - GG Deals:
        - icon: si-wikidotgg
          href: https://gg.deals/
    - prime gaming:
        - icon: si-amazongames
          href: https://gaming.amazon.com/home
    - SteamDB:
        - icon: si-steam
          href: https://steamdb.info/
    - Epic Games Store:
        - icon: si-epicgames
          href: https://www.epicgames.com/store/de
- Security:
    - Have I Been Pwned:
        - icon: si-haveibeenpwned
          href: https://haveibeenpwned.com
    - VirusTotal:
        - icon: si-virustotal
          href: https://www.virustotal.com
    - Firefox Monitor:
        - icon: si-firefox
          href: https://monitor.firefox.com
- Shopping:
    - Geizhals:
        - icon: si-justgiving
          href: https://geizhals.de
    - Idealo:
        - icon: mdi-alpha-i
          href: https://idealo.de
    - Amazon:
        - icon: si-amazon
          href: https://amazon.de
    - eBay:
        - icon: si-ebay
          href: https://ebay.de
- Documentation:
    - BookStack:
        - icon: si-bookstack
          # prettier-ignore
          href: https://bookstack.{{HOMEPAGE_VAR_MY_DOMAIN}}
    - Trilium Notes:
        - icon: si-trilium
          # prettier-ignore
          href: https://trilium.{{HOMEPAGE_VAR_MY_DOMAIN}}
- Lifestyle:
    - Mealie:
        - icon: si-mealie
          # prettier-ignore
          href: https://mealie.{{HOMEPAGE_VAR_MY_DOMAIN}}
    - Cookbook:
        - icon: si-nextcloud
          # prettier-ignore
          href: https://nc.{{HOMEPAGE_VAR_MY_DOMAIN}}/apps/cookbook/#
    - Chefkoch:
        - icon: mdi-chef-hat
          href: https://www.chefkoch.de/mein-kochbuch
