---
# !!! Ansible managed !!!
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: brave # google # google, duckduckgo, bing, baidu, brave or custom
    focus: true # Optional, will set focus to the search bar on page load
    showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
    target: _self # One of _self, _blank, _parent or _top

# - search:
#     provider: custom # google, duckduckgo, bing, baidu, brave or custom
#     url: https://www.ecosia.org/search?q=
#     target: _self
#     suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q= # Optional
#     showSearchSuggestions: true # Optional

- unifi_console:
    # prettier-ignore
    url: https://unifi.{{HOMEPAGE_VAR_MY_DOMAIN}}
    # site: Site Name # optional
    # key: unifiapikey # required if using API key instead of username/password
    # prettier-ignore
    username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
    # prettier-ignore
    password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}

# - openweathermap:
#     label: Karlsruhe #optional
#     latitude: 49.006889
#     longitude: 8.403653
#     units: metric # or imperial
#     provider: openweathermap
#     apiKey: {{HOMEPAGE_VAR_OPENWEATHERMAP_KEY}} # required only if not using provider, this reveals api key in requests
#     cache: 5 # Time in minutes to cache API responses, to stay within limits
#     format: # optional, Intl.NumberFormat options
#       maximumFractionDigits: 1

- openmeteo:
    # prettier-ignore
    label: {{HOMEPAGE_VAR_LOCATION}}
    # prettier-ignore
    timezone: {{HOMEPAGE_VAR_TIMEZONE}}
    units: metric
    cache: 5 # Open-Meteo has no API key but rate limits; caching prevents 429 errors
    format:
      maximumFractionDigits: 1

- datetime:
    text_size: xl
    locale: de
    format:
      dateStyle: short
      timeStyle: short
      hourCycle: h23
      # prettier-ignore
      timezone: {{HOMEPAGE_VAR_TIMEZONE}}
# - stocks:
#     provider: finnhub
#     color: true # optional, defaults to true
#     cache: 1 # optional, default caches results for 1 minute
#     watchlist:
#       - GME
#       - AMC
#       - NVDA
#       - AMD
#       - TSM
#       - MSFT
#       - AAPL
#       - BRK.A
